// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVDzzdEMo0cG4mUk_q4eDn2FuWHEFjjrQ',
    appId: '1:516526486431:web:5842322e08edba722703aa',
    messagingSenderId: '516526486431',
    projectId: 'riseup-de213',
    authDomain: 'riseup-de213.firebaseapp.com',
    storageBucket: 'riseup-de213.firebasestorage.app',
    measurementId: 'G-4Q31WR4CWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgmwCb_R9qkmT3enLrtoMOMpih7ncouTc',
    appId: '1:516526486431:android:5c7624eb66d6456e2703aa',
    messagingSenderId: '516526486431',
    projectId: 'riseup-de213',
    storageBucket: 'riseup-de213.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLn67JPU-Ag7ShQyGHY5uP2519ZUho5oo',
    appId: '1:516526486431:ios:f9264f48b4b8e9892703aa',
    messagingSenderId: '516526486431',
    projectId: 'riseup-de213',
    storageBucket: 'riseup-de213.firebasestorage.app',
    iosBundleId: 'com.example.riseUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLn67JPU-Ag7ShQyGHY5uP2519ZUho5oo',
    appId: '1:516526486431:ios:f9264f48b4b8e9892703aa',
    messagingSenderId: '516526486431',
    projectId: 'riseup-de213',
    storageBucket: 'riseup-de213.firebasestorage.app',
    iosBundleId: 'com.example.riseUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVDzzdEMo0cG4mUk_q4eDn2FuWHEFjjrQ',
    appId: '1:516526486431:web:84e3f91f61f3110f2703aa',
    messagingSenderId: '516526486431',
    projectId: 'riseup-de213',
    authDomain: 'riseup-de213.firebaseapp.com',
    storageBucket: 'riseup-de213.firebasestorage.app',
    measurementId: 'G-MM0SPNWCQT',
  );
}
